### ISSUE TITLE
Не всегда запускается мелодия

### ISSUE THREAD

**Issue by CRAZY41** [duckpicker/GenshinQuartetPlayer#1]
Заметил баг после последнего обновления Геншина. Иногда мелодия отказывается играть после n-ного количества сворачиваний игры. После - нужно: 
а) Перезапустить приложение
б) Потыкать несколько раз в обновление песен в клиенте и несколько раз на "открыть окно"

**Comment by duckpicker** [comment]
Скорее всего проблема в том, что между открытием окна геншина и началом игры нет никакой задержки. Сейчас заметил, что даже у меня периодически случается пролаг и файл не играется. Думаю на каких-нибудь слабых компах это намного заметнее. и чаще происходит. Сейчас сделаю фикс, напишешь помогло или нет.

**Comment by CRAZY41** [comment]
> Скорее всего проблема в том, что между открытием окна геншина и началом игры нет никакой задержки. Сейчас заметил, что даже у меня периодически случается пролаг и файл не играется. Думаю на каких-нибудь слабых компах это намного заметнее. и чаще происходит. Сейчас сделаю фикс, напишешь помогло или нет.

Ну, комп-то мой не оскробляй с 64гб памяти и 5800x 
Но фикс работает, тикет можно закрывать :)
